pipeline {
    environment {
        registry = "aymanazzam63/app"
        registryCredential = 'dockerhub_user'
        dockerImage = ''
    }
    agent any
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: '1.0', description: 'Image tag like 1.0 or 2.0, ...etc')
    }
    stages {
        stage('Building the image') {
            steps{
                dir('./docker/App/'){
                    script {
                        dockerImage = docker.build(registry + ":" + currentBuild.number)
                    }
                }
            }
        }
        stage('Upload the image to docker hub') {
            steps{
                script {
                        docker.withRegistry('', registryCredential ) {
                            dockerImage.push()
                        }
                }
            }
        }
        stage('Invoke deployment pipeline') {
            steps{
                build job: 'isolution - Deployment', parameters: [string(name: 'IMAGE_TAG', value: ${currentBuild.number})]
            }
        }
    }
}