apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment
  namespace: development

spec:
  replicas: 3
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: aymanazzam63/app:{{ .Values.imageTag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: VAULT_ADDR
              value: "http://$(VAULT_SERVICE_SERVICE_HOST):$(VAULT_SERVICE_SERVICE_PORT)"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: password
            - name: DB_HOST
              value: $(MYSQL_SERVICE_SERVICE_HOST)
            - name: DB_PORT
              value: $(MYSQL_SERVICE_SERVICE_PORT)
          resources:
            limits:
              cpu: 500m
              memory: "256Mi"
            requests:
              cpu: 200m
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http