apiVersion: apps/v1
kind: Deployment

metadata:
  name: vault-deployment
  namespace: development

spec:
  replicas: 1
  selector:
    matchLabels:
      component: vault
  template:
    metadata:
      labels:
        component: vault
    spec:
      containers:
      - name: vault
        image: vault:1.13.3
        ports:
        - containerPort: 8200
        resources:
            requests:
              cpu: 250m
              memory: 750Mi
        env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: password