apiVersion: v1
kind: Service

metadata:
  name: app-node-port
  namespace: development

spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 31616
  selector:
    component: app