apiVersion: v1
kind: Service

metadata:
  name: grafana-service
  namespace: monitoring

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    component: grafana