apiVersion: v1
kind: Service

metadata:
  name: web-service
  namespace: development

spec:
  type: LoadBalancer
  selector:
    component: nginx
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 32626